name: Terraform Apply
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-south-1
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: |
          cd 'External Secrets'
          terraform init
      - name: Terraform Plan
        env:
          TF_VAR_april_client_id: ${{ secrets.APRIL_CLIENT_ID }}
          TF_VAR_april_client_secret: ${{ secrets.APRIL_CLIENT_SECRET }}
          TF_VAR_ista_edge: ${{ secrets.ISTA_EDGE }}
          TF_VAR_scope: ${{ secrets.SCOPE }}
          TF_VAR_tric_emea: ${{ secrets.TRIC_EMEA}}
          TF_VAR_tric_us: ${{secrets.TRIC_US}}
        shell: bash
        run: |
          cd 'External Secrets'
          terraform plan
      - name: Terraform Destroy
        env:
          TF_VAR_april_client_id: ${{ secrets.APRIL_CLIENT_ID }}
          TF_VAR_april_client_secret: ${{ secrets.APRIL_CLIENT_SECRET }}
          TF_VAR_ista_edge: ${{ secrets.ISTA_EDGE }}
          TF_VAR_scope: ${{ secrets.SCOPE }}
          TF_VAR_tric_emea: ${{ secrets.TRIC_EMEA}}
          TF_VAR_tric_us: ${{secrets.TRIC_US}}
        shell: bash
        run: |
          cd 'External Secrets'
          terraform destroy -auto-approve
#      - name: Terraform Apply
#        run: terraform apply -auto-approve
